globals:
  output_folder: "./results"
  dataset: "NAB"


models:
  TS2Vec:
    eval: False
    model_name: "TS2Vec"
    seq_len: 32
    stride: 32
    windows: True
    verbose: True
    device: "cpu"
    save_score: False
    model_path: "./model/ts2vec/model_weights.pth"
    print_results: False
    thresh: 12
    mode_auto: True
    n_channels : 12
    modif_score: False

  lagllama_mahala:
    eval: False
    model_name: "lagllama_mahala"
    seq_len: 32
    stride: 32
    windows: True
    verbose: True
    device: "cuda"
    save_score: False
    print_results: False
    model_path: "./model/lagllama/lag-llama.ckpt"
    thresh: 12
    mode_auto: True
    n_channels : 16
    modif_score: False
  
  Donut:
    eval: True
    model_name: "Donut"
    seq_len: 120
    windows: False
    verbose: True
    "test_size": 0.8
    device: "cuda"
    save_score: False
    n_epoch: 100

